#define ActorSlot_AttachToParentByIndex_02035b4c ActorSlot_AttachToParentByIndex
#define ActorSlot_AttachToParent_02035b74 ActorSlot_AttachToParent
#define g_actorRegistry_0206083c gActorRegistry
#include "src/arm9/shared_engine/ActorSlot_AttachToParentByIndex_02035b4c.c"
