#define AdjustVectorTowardNormal_0204ac64 AdjustVectorTowardNormal
#define VEC_DotProduct_01ff9e6c VEC_DotProduct
#define VEC_MultAdd_01ffa09c VEC_MultAdd
#include "src/arm9/math/AdjustVectorTowardNormal_0204ac64.c"
