#define AreAxesMutuallyEnclosing_0203dde0 AreAxesMutuallyEnclosing
#define IsAxisInsideVectorCone_0203dd00 IsAxisInsideVectorCone
#define func_0204aea8 GetUnitRejectionFromAxis
#include "src/arm9/spatial_queries/AreAxesMutuallyEnclosing_0203dde0.c"
