#define BlendVectorsBySqrtComplementPositive_02048bbc BlendVectorsBySqrtComplementPositive
#define BlendVectorsBySqrtComplement_0204b59c BlendVectorsBySqrtComplement
#include "src/arm9/math/BlendVectorsBySqrtComplementPositive_02048bbc.c"
