#define ApplyQuaternionCorrectionToMatrix_0202f090 ApplyQuaternionCorrectionToMatrix
#define CaptureGeometryMatrices_02019d00 NNS_G3dGetCurrentMtx
#define CaptureTrackedNodeMatrixCallback_0202f13c CaptureTrackedNodeMatrixCallback
#include "src/arm9/model_animation/CaptureTrackedNodeMatrixCallback_0202f13c.c"
