#define ClipRayAgainstPlane_01fff6c8 ClipRayAgainstPlane
#define FX_DivFx64c_01ff9c94 FX_DivFx64c
#define VEC_DotProduct_01ff9e6c VEC_DotProduct
#include "src/itcm/spatial_queries/ClipRayAgainstPlane_01fff6c8.c"
