#define ComputePolygonEdgeFrames_0203b0b4 ComputePolygonEdgeFrames
#define VEC_CrossProduct_01ff9ea8 VEC_CrossProduct
#define VEC_Subtract_01ff9e3c VEC_Subtract
#define func_01ff9f88 VEC_Normalize
#include "src/arm9/spatial_queries/ComputePolygonEdgeFrames_0203b0b4.c"
