#define CTRDG_Enable_020124e8 CTRDG_Enable
#define CTRDGi_HasValidModuleInfo_02012320 CTRDGi_HasValidModuleInfo
#define DC_FlushAll_020033e0 DC_FlushAll
#define DC_WaitWriteBufferEmpty_02003470 DC_WaitWriteBufferEmpty
#define OS_DisableDCacheForProtectionRegion_02003ba0 OS_DisableDCacheForProtectionRegion
#define OS_DisableICacheForProtectionRegion_02003b80 OS_DisableICacheForProtectionRegion
#define OS_DisableInterrupts_02004938 OS_DisableInterrupts
#define OS_DisableWriteBufferForProtectionRegion_02003bd4 OS_DisableWriteBufferForProtectionRegion
#define OS_EnableDCacheForProtectionRegion_02003b90 OS_EnableDCacheForProtectionRegion
#define OS_EnableICacheForProtectionRegion_02003b70 OS_EnableICacheForProtectionRegion
#define OS_EnableWriteBufferForProtectionRegion_02003bc4 OS_EnableWriteBufferForProtectionRegion
#define OS_RestoreInterrupts_0200494c OS_RestoreInterrupts
#define OS_SetDPermissionsForProtectionRegion_02003bb0 OS_SetDPermissionsForProtectionRegion
#include "src/arm9/library_nitro_ctrdg/CTRDG_Enable_020124e8.c"
