#define DispObj_MirrorOam_0204e278 DispObj_MirrorOam
#define Oam_GetObjHeight Sprite_GetHeightFromOamAttributes
#define Oam_GetObjWidth Sprite_GetWidthFromOamAttributes
#include "src/arm9/shared_engine/DispObj_MirrorOam_0204e278.c"
