#define AcquireRecordSlot_02051d3c AcquireRecordSlot
#define CloseRecordManager_02051cdc ReleaseRecordManager
#define FillSelectionRecordFromGroup_0204f8dc FillSelectionRecordFromGroup
#define GetOverlaySelectionRecord_0204f768 GetOverlaySelectionRecord
#define GetRecordSlotPair0Entry_02051ec8 GetRecordSlotPair0Entry
#define OpenRecordManager_02051c80 AcquireRecordManager
#define PackNamedRecordEntry_0204f63c PackNamedRecordEntry
#define ReleaseRecordSlot_02051dfc ReleaseRecordSlot
#include "src/arm9/overlay_selection/FillSelectionRecordFromGroup_0204f8dc.c"
