#define DecodeCompressedRotationITCM_01ffd56c DecodeCompressedRotationITCM
#define GetJointSRTAnimResult_01ffd6ac GetJointSRTAnimResult
#define ModelAnimation_ApplyDefaultJointPosition_02038ea8 ModelAnimation_ApplyDefaultJointPosition
#define ModelAnimation_ApplyDefaultJointScale_02038f3c ModelAnimation_ApplyDefaultJointScale
#define ModelAnimation_SampleJointScale_020393d4 ModelAnimation_SampleJointScale
#define ModelAnimation_SampleJointTranslation_02039130 ModelAnimation_SampleJointTranslation
#define NNSi_G3dGetMdlRot_02038fd0 NNSi_G3dGetMdlRot
#define SampleJointRotationStreamITCM_01ffd180 SampleJointRotationStreamITCM
#include "src/itcm/library_nns_g3d/GetJointSRTAnimResult_01ffd6ac.c"
