#define GetPerpendicularVector_0204ad4c GetPerpendicularVector
#define PickPerpendicularAxis_0204acb0 PickPerpendicularAxis
#define VEC_CrossProduct_01ff9ea8 VEC_CrossProduct
#include "src/arm9/math/GetPerpendicularVector_0204ad4c.c"
