#define GetCapsuleProjectedExtent_0203d684 GetCapsuleProjectedExtent
#define GetMaxProjectedSpread_0203d7f4 GetMaxProjectedSpread
#define GetObbProjectedRadius_0203d4d0 GetObbProjectedRadius
#define GetShapeProjectedRadius_0203b2cc GetShapeProjectedRadius
#define VEC_DotProduct_01ff9e6c VEC_DotProduct
#define VEC_Subtract_01ff9e3c VEC_Subtract
#include "src/arm9/spatial_queries/GetShapeProjectedRadius_0203b2cc.c"
