#define DivideVecByLength_0204a6ac DivideVecByLength
#define GetPerpendicularVector_0204ad4c GetPerpendicularVector
#define GetUnitCrossReportDegenerate_0204ab10 GetUnitCrossReportDegenerate
#define VEC_CrossProduct_01ff9ea8 VEC_CrossProduct
#define VEC_Mag_01ff9f28 VEC_Mag
#define VEC_Normalize_01ff9f88 VEC_Normalize
#include "src/arm9/math/GetUnitCrossReportDegenerate_0204ab10.c"
