#define GFXi_EnqueueCommand NNS_GfdRegisterNewVramTransferTask
#define Gfx_EnqueueBgScreenUpload_0202aec0 Gfx_EnqueueBgScreenUpload
#include "src/arm9/shared_engine/Gfx_EnqueueBgScreenUpload_0202aec0.c"
