#define IsAxisInsideVectorCone_0203dd00 IsAxisInsideVectorCone
#define VEC_CrossProduct_01ff9ea8 VEC_CrossProduct
#define VEC_DotProduct_01ff9e6c VEC_DotProduct
#include "src/arm9/spatial_queries/IsAxisInsideVectorCone_0203dd00.c"
