#define ModelAnimation_ApplyDefaultJointScale_02038f3c ModelAnimation_ApplyDefaultJointScale
#define g_modelRenderState NNS_G3dRS
#include "src/arm9/model_animation/ModelAnimation_ApplyDefaultJointScale_02038f3c.c"
