#define Archive_GetMember NestedPointer_GetFirstWord
#define Coll_ResolveModelBlobPointers InitMeshData
#define ModelGroup_Open_0203510c ModelGroup_Open
#define NNSi_FndAllocFromDefaultExpHeap NNSi_FndAllocFromDefaultHeap
#define Obj_GetIndirectWord IndexedPointer_GetFirstWord
#include "src/arm9/shared_engine/ModelGroup_Open_0203510c.c"
