#define ModelAnimation_ApplyDefaultJointPosition_02038ea8 ModelAnimation_ApplyDefaultJointPosition
#define g_modelRenderState NNS_G3dRS
#include "src/arm9/model_animation/ModelAnimation_ApplyDefaultJointPosition_02038ea8.c"
