#define DecodeCompressedRotationITCM_01ffd56c DecodeCompressedRotationITCM
#define ModelAnimation_ApplyDefaultJointPosition_02038ea8 ModelAnimation_ApplyDefaultJointPosition
#define ModelAnimation_ApplyDefaultJointScale_02038f3c ModelAnimation_ApplyDefaultJointScale
#define ModelAnimation_BlendJointRotation_02039728 ModelAnimation_BlendJointRotation
#define ModelAnimation_BlendJointScale_020395a8 ModelAnimation_BlendJointScale
#define ModelAnimation_BlendJointTranslation_02039280 ModelAnimation_BlendJointTranslation
#define ModelAnimation_GetJointSRTResult_02039a54 ModelAnimation_GetJointSRTResult
#define NNSi_G3dGetMdlRot_02038fd0 NNSi_G3dGetMdlRot
#include "src/arm9/model_animation/ModelAnimation_GetJointSRTResult_02039a54.c"
