#define FlushGeometryCommandBuffer_01ffa204 FlushGeometryCommandBuffer
#define NNS_G3dDraw1Mat1Shp_01fff3dc NNS_G3dDraw1Mat1Shp
#define QueueOrSendGeometryCommand_01ffa37c NNS_G3dGeBufferOP_N
#define g_texMtxSendFuncs_02055d7c gMaterialAnimationDispatch
#include "src/itcm/library_nns_g3d/NNS_G3dDraw1Mat1Shp_01fff3dc.c"
