#define GetOverlaySelectionRecord_0204f768 GetOverlaySelectionRecord
#define PackNamedRecordEntry_0204f63c PackNamedRecordEntry
#define PackSelectionRecordEntry_0204fda4 PackSelectionRecordEntry
#include "src/arm9/overlay_selection/PackSelectionRecordEntry_0204fda4.c"
