#define ProjectPositionAtTimeMaybeVertical_0204b790 ProjectPositionAtTimeMaybeVertical
#define ProjectPositionAtTime_0204a7bc ProjectPositionAtTime
#include "src/arm9/math/ProjectPositionAtTimeMaybeVertical_0204b790.c"
