#define InitSegmentFromEndpoints_0203b1f0 InitSegmentFromEndpoints
#define RefreshShapeDerivedData_0203eeac RefreshShapeDerivedData
#define UpdateBoxAxisAlignedFlag_0203b1c0 UpdateBoxAxisAlignedFlag
#define data_020559c0 gCollisionBoundsDispatch
#define func_0203b0b4 ComputePolygonEdgeFrames
#include "src/arm9/spatial_queries/RefreshShapeDerivedData_0203eeac.c"
