#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseRecordManager_02051cdc ReleaseRecordManager
#define ReleaseRecordSlot_02051dfc ReleaseRecordSlot
#define ZeroHalfThenFree_0202cd78 ZeroHalfThenFree
#define g_recordManager_020613d0 gRecordManager
#include "src/arm9/indexed_records/ReleaseRecordManager_02051cdc.c"
