#define ResetGraphicsTransform_0202fdf4 ResetGraphicsTransform
#define func_01ff80e4 GXi_FlushCommandList
#define func_01ffa37c NNS_G3dGeBufferOP_N
#define func_02019188 NNS_G3dGlbFlushP
#define graphics_state NNS_G3dGlb
#define rotation_matrix NNS_G3dGlb_prmBaseRot
#include "src/arm9/graphics_and_transforms/ResetGraphicsTransform_0202fdf4.c"
