#define Ov105_SetCommandArg SetCommandArg
#define Ov105_WMi_CheckStateEx WMi_CheckStateEx
#define Ov105_WMi_SendCommand WMi_SendCommand
#define RunTransitionSlotB_0201193c RunTransitionSlotB
#include "src/arm9/shared_engine/RunTransitionSlotB_0201193c.c"
