#define ScriptCmd_SetElemFieldFromOperand_0202651c ScriptCmd_SetElemFieldFromOperand
#define ScriptCmd_SetElemField_02025e18 ScriptCmd_SetElemField
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/arm9/shared_engine/ScriptCmd_SetElemFieldFromOperand_0202651c.c"
