#define ScriptCmd_LoadFileToSlot_020267fc ScriptCmd_LoadFileToSlot
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#define func_02025dac ByteCode_ResolveOperand
#define func_0202cc6c Msg_OpenContainerAndReadHeader
#include "src/arm9/shared_engine/ScriptCmd_LoadFileToSlot_020267fc.c"
