#define ScriptCmd_CopyOperandOrInvokeHandler_020262cc ScriptCmd_CopyOperandOrInvokeHandler
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#define ScriptVm_ResolveOperand_02025d08 ScriptVm_ResolveOperand
#include "src/arm9/shared_engine/ScriptCmd_CopyOperandOrInvokeHandler_020262cc.c"
