#define DispCnt_ApplyPendingMode GX_DispOn
#define Ov001_SetupSubScreenBanks SetupSubScreenBanks
#define SetupDisplayRegs_020299f4 SetupDisplayRegs
#include "src/arm9/shared_engine/SetupDisplayRegs_020299f4.c"
