#define GetOverlaySelectionRecord_0204f768 GetOverlaySelectionRecord
#define SetupFlaggedSelectionRecords_0204f778 SetupFlaggedSelectionRecords
#define func_0204fbcc ApplySelectionStatScaling
#define func_0204fda4 PackSelectionRecordEntry
#include "src/arm9/overlay_selection/SetupFlaggedSelectionRecords_0204f778.c"
