#define NegateVecFx32_0204aa40 NegateVecFx32
#define SweepCappedCylinderAgainstSphereSwapped_02041bb4 SweepCappedCylinderAgainstSphereSwapped
#define SweepSphereAgainstCappedCylinder_02042b84 SweepSphereAgainstCappedCylinder
#include "src/arm9/spatial_queries/SweepCappedCylinderAgainstSphereSwapped_02041bb4.c"
