#define SweepAlongProjectedAxis_020481c4 SweepAlongProjectedAxis
#define SweepIntervalOnAxis_01fff6c8 ClipRayAgainstPlane
#define VEC_DotProduct_01ff9e6c VEC_DotProduct
#include "src/arm9/spatial_queries/SweepAlongProjectedAxis_020481c4.c"
