#define AcquireRecordSlot_02051d3c AcquireRecordSlot
#define CloseRecordManager_02051cdc ReleaseRecordManager
#define GetOverlaySelectionRecord_0204f768 GetOverlaySelectionRecord
#define GetRecordSlotPair0Entry_02051ec8 GetRecordSlotPair0Entry
#define OpenRecordManager_02051c80 AcquireRecordManager
#define ReleaseRecordSlot_02051dfc ReleaseRecordSlot
#define SyncSelectionRecordFromSlotEntry_0204fabc SyncSelectionRecordFromSlotEntry
#include "src/arm9/overlay_selection/SyncSelectionRecordFromSlotEntry_0204fabc.c"
