#define TestCylinderAgainstCylinderSwapped_0203b628 TestCylinderAgainstCylinderSwapped
#define TestCylinderAgainstCylinder_020410a0 TestCylinderAgainstCylinder
#include "src/arm9/spatial_queries/TestCylinderAgainstCylinderSwapped_0203b628.c"
