#define TestCylinderAgainstSegment_0203b5d4 TestCylinderAgainstSegment
#define TestSegmentAgainstCylinder_02040548 TestCapsuleAgainstCylinder
#include "src/arm9/spatial_queries/TestCylinderAgainstSegment_0203b5d4.c"
