#define TestCylinderAgainstPolygon_0203c6bc TestCylinderAgainstPolygon
#define TestPolygonAgainstCylinder_0203b698 TestPolygonAgainstCylinder
#include "src/arm9/spatial_queries/TestPolygonAgainstCylinder_0203b698.c"
