#define TestCylinderAgainstSphere_0203b5f0 TestCylinderAgainstSphere
#define TestSphereAgainstCylinder_0203f658 TestSphereAgainstCylinder
#include "src/arm9/spatial_queries/TestCylinderAgainstSphere_0203b5f0.c"
