#define Ov105_SetCommandArg SetCommandArg
#define Ov105_WMi_CheckStateEx WMi_CheckStateEx
#define Ov105_WMi_SendCommand WMi_SendCommand
#define Ov105_WmCheckParentParameter WmCheckParentParameter
#define WM_SetParentParameter_02011738 WM_SetParentParameter
#include "src/arm9/library_nitro_wm/WM_SetParentParameter_02011738.c"
