#define Actor_AnyAnimSlotBusy_020cd124 Actor_AnyAnimSlotBusy
#define Actor_GetModelPosition_020cd0d8 Actor_GetModelPosition
#define Actor_PlaySurfaceSound_020cca14 Actor_PlaySurfaceSound
#define LookupKindTableValue_020a8fc8 LookupKindTableValue
#define SpawnSoundSlot_0204da8c SpawnSoundSlot
#include "src/ov059/unclassified_helpers/Actor_PlaySurfaceSound_020cca14.c"
