#define Actor_ExitCommandMode_020cb968 Actor_ExitCommandMode
#define EntryQueue_Clear_020cf3dc EntryQueue_Clear
#define GetGroupSlotValue_020a8f1c GetGroupSlotValue
#define SetSlotEntryValue_020a8f4c SetSlotEntryValue
#include "src/ov059/unclassified_helpers/Actor_ExitCommandMode_020cb968.c"
