#define Actor_FreeAttachedModels_020c8b50 Actor_FreeAttachedModels
#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#include "src/ov059/unclassified_helpers/Actor_FreeAttachedModels_020c8b50.c"
