#define EffectGroup_RewindEntry_020cb9ec EffectGroup_RewindEntry
#define StopAndClearSoundEmitter_020a8e14 StopAndClearSoundEmitter
#define func_ov021_020a8eec GetGroupMemberData
#include "src/ov059/unclassified_helpers/EffectGroup_RewindEntry_020cb9ec.c"
