#define EffectSet_Release_020cf1d8 EffectSet_Release
#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseCallbackOwnedBuffer_020aafac ReleaseCallbackOwnedBuffer
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#include "src/ov059/unclassified_helpers/EffectSet_Release_020cf1d8.c"
