#define MarkerList_ProjectToScreen_020cf65c MarkerList_ProjectToScreen
#define ProjectWorldToScreenFx_0206ad34 ProjectWorldToScreenFx
#define TargetKey_GetPosition_020cf0a4 TargetKey_GetPosition
#include "src/ov059/unclassified_helpers/MarkerList_ProjectToScreen_020cf65c.c"
