#define GetWorldMeshNamedEntry_0203625c GetWorldMeshNamedEntry
#define ProbeLinkedMeshEntries_020cb8cc ProbeLinkedMeshEntries
#include "src/ov059/unclassified_helpers/ProbeLinkedMeshEntries_020cb8cc.c"
