#define CopyFieldUnitSlotFrame_020a5ef4 CopyFieldUnitSlotFrame
#define GetFieldUnitSlotRecord_020a5cfc GetFieldUnitSlotRecord
#define MIi_CpuCopyFast_01ff878c MIi_CpuCopyFast
#include "src/ov016/field_objects/CopyFieldUnitSlotFrame_020a5ef4.c"
