#define PlaceFieldObjectAtPosition_020a2b28 PlaceFieldObjectAtPosition
#define PlaceFieldObjectNode_020a2aac PlaceFieldObjectNode
#include "src/ov016/field_objects/PlaceFieldObjectAtPosition_020a2b28.c"
