#define ScriptVm_ConsumeOperandInt_020a1de0 ScriptVm_ConsumeOperandInt
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov016/script_commands/ScriptVm_ConsumeOperandInt_020a1de0.c"
