#define CheckSideOffsetInRange_0206b3d4 CheckSideOffsetInRange
#define FixedPointMultiply12 FX_Mul
#define VEC_Subtract_01ff9e3c VEC_Subtract
#include "src/ov001/shared_engine/CheckSideOffsetInRange_0206b3d4.c"
