#define FieldObject_SetProbeSphere_0207f8fc FieldObject_SetProbeSphere
#define Model_SetAllPolygonIds_0201a8c0 NNS_G3dMdlSetMdlPolygonIDAll
#define SetAllMaterialsPolyAttrMask_0201a3c4 NNSi_G3dModifyPolygonAttrMask
#define SetObjectProbeSphere_020361b8 SetObjectProbeSphere
#include "src/ov001/field_objects/FieldObject_SetProbeSphere_0207f8fc.c"
