#define CloseSceneMessage_0206fe7c CloseSceneMessage
#define DrawNextTypewriterGlyph_0206feb4 DrawNextTypewriterGlyph
#define FlushAndCloseSceneMessage_0206fef4 FlushAndCloseSceneMessage
#include "src/ov001/text_rendering/FlushAndCloseSceneMessage_0206fef4.c"
