#define FreeScriptWorkBuffers_0208da5c FreeScriptWorkBuffers
#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#include "src/ov001/scripted_actor_behavior/FreeScriptWorkBuffers_0208da5c.c"
