#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseOwnerResource_0207f20c ReleaseOwnerResource
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#include "src/ov001/unclassified_helpers/ReleaseOwnerResource_0207f20c.c"
