#define ActorChannel_SetStateFields_0208b870 ActorChannel_SetStateFields
#define ScriptCmd_SetActorChannelState_0208d50c ScriptCmd_SetActorChannelState
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/shared_engine/ScriptCmd_SetActorChannelState_0208d50c.c"
