#define ScriptCmd_UpdateBrightnessFade_0208d10c ScriptCmd_UpdateBrightnessFade
#define ScriptCmd_UpdateScreenBrightnessFades_0208d1ec ScriptCmd_UpdateScreenBrightnessFades
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/scripted_actor_behavior/ScriptCmd_UpdateScreenBrightnessFades_0208d1ec.c"
