#define ScriptCmd_AdjustItemCount_02065dc8 ScriptCmd_AdjustItemCount
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/unclassified_helpers/ScriptCmd_AdjustItemCount_02065dc8.c"
