#define ScriptCmd_SetFieldObjectsFlag_020659dc ScriptCmd_SetFieldObjectsFlag
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/shared_engine/ScriptCmd_SetFieldObjectsFlag_020659dc.c"
