#define ActorObject_ResetSecondarySlots_0208a704 ActorObject_ResetSecondarySlots
#define ActorObject_SetSecondarySlot_0208a724 ActorObject_SetSecondarySlot
#define ScriptCmd_ReturnValue_02025960 ScriptCmd_ReturnValue
#define ScriptCmd_SetActorSecondarySlot_0208ea24 ScriptCmd_SetActorSecondarySlot
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/scripted_actor_behavior/ScriptCmd_SetActorSecondarySlot_0208ea24.c"
