#define ScriptCmd_BeginBrightnessFade_0208d184 ScriptCmd_BeginBrightnessFade
#define ScriptCmd_SetElemField_02025e18 ScriptCmd_SetElemField
#define ScriptCmd_StartScreenBrightnessFade_0208d084 ScriptCmd_StartScreenBrightnessFade
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/scripted_actor_behavior/ScriptCmd_BeginBrightnessFade_0208d184.c"
