#define GetOverlaySelectionRecord_0204f768 GetOverlaySelectionRecord
#define ScriptCmd_RestoreSelectionRecordValue_02065f8c ScriptCmd_RestoreSelectionRecordValue
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/shared_engine/ScriptCmd_RestoreSelectionRecordValue_02065f8c.c"
