#define ScriptCmd_ReturnValue_02025960 ScriptCmd_ReturnValue
#define ScriptCmd_StartActorRotation_0208dc4c ScriptCmd_StartActorRotation
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#define StartActorMotionTo_0208a4b8 StartActorMotionTo
#define func_02025dac ByteCode_ResolveOperand
#include "src/ov001/scripted_actor_behavior/ScriptCmd_StartActorRotation_0208dc4c.c"
