#define ScriptCmd_BindActorTarget_0208ddc8 ScriptCmd_BindActorTarget
#define ScriptCmd_ReturnValue_02025960 ScriptCmd_ReturnValue
#define ScriptCmd_SetElemFieldIfFlagSet_0208de1c ScriptCmd_SetElemFieldIfFlagSet
#define ScriptCmd_SetElemField_02025e18 ScriptCmd_SetElemField
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#define func_02036240 ActorRegistry_GetEntityByIndex
#include "src/ov001/scripted_actor_behavior/ScriptCmd_BindActorTarget_0208ddc8.c"
