#define ActorChannel_ConfigureAndPlay_0208b9cc ActorChannel_ConfigureAndPlay
#define ScriptCmd_PlayActorChannel_0208d560 ScriptCmd_PlayActorChannel
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/shared_engine/ScriptCmd_PlayActorChannel_0208d560.c"
