#define ActorChannel_QueueRequest_0208bcc0 ActorChannel_QueueRequest
#define ScriptCmd_QueueCameraAngleTransition_0208ee0c ScriptCmd_QueueCameraAngleTransition
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/scripted_actor_behavior/ScriptCmd_QueueCameraAngleTransition_0208ee0c.c"
