#define ScriptCmd_SetSubScreenVisible_0208e9ec ScriptCmd_SetSubScreenVisible
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#include "src/ov001/scripted_actor_behavior/ScriptCmd_SetSubScreenVisible_0208e9ec.c"
