#define FindNearestStageEntry_02099328 FindNearestStageEntry
#define SyncNearestEntryPosition_0208f6bc SyncNearestEntryPosition
#define SyncStageEntryPosition_02098fbc SyncStageEntryPosition
#include "src/ov001/shared_engine/SyncNearestEntryPosition_0208f6bc.c"
