#!/usr/bin/env python3
"""Regenerate PROGRESS.md (per-module progress) from tools/audit_progress.py."""
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import audit_progress  # noqa: E402
from project import ROOT  # noqa: E402


def unit_key(unit):
    m = re.match(r"ov(\d+)", unit)
    return (1, int(m.group(1))) if m else (0, ["main", "itcm", "dtcm"].index(unit) if unit in ("main", "itcm", "dtcm") else 9)


def status_mark(c_count, total):
    return "DONE" if c_count == total else "PART" if c_count else "TODO"


def byte_progress(functions):
    c = sum(f["size"] for f in functions if f["category"] == "c_decompiled_matched")
    return c, sum(f["size"] for f in functions)


def main():
    functions, _unknown = audit_progress.classify_functions()
    stats = defaultdict(Counter)
    sizes = defaultdict(Counter)
    for f in functions:
        stats[f["unit"]][f["category"]] += 1
        stats[f["unit"]]["total"] += 1
        sizes[f["unit"]]["total"] += f["size"]
        if f["category"] == "c_decompiled_matched":
            sizes[f["unit"]]["c"] += f["size"]

    lines = [
        "# Progress by module",
        "",
        "Auto-generated by `python tools/progress.py`.",
        "",
        "Only `C matched` counts as real C decompilation progress; see",
        "[docs/PROGRESS_POLICY.md](docs/PROGRESS_POLICY.md). `Named` functions have",
        "an identified name (NitroSDK, NNS, MSL, ...) but no source yet.",
        "",
        "| Module | C matched | ASM stubs | Named | Not started | Total | C % | C bytes % |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
    ]
    totals = Counter()
    for unit in sorted(stats, key=unit_key):
        row = stats[unit]
        total = row["total"]
        c = row["c_decompiled_matched"]
        for k in ("c_decompiled_matched", "asm_stub_matched", "named", "todo", "total"):
            totals[k] += row[k]
        lines.append("| %s %s | %d | %d | %d | %d | %d | %.1f%% | %.1f%% |" % (
            status_mark(c, total), unit, c, row["asm_stub_matched"], row["named"], row["todo"], total,
            100.0 * c / total if total else 100.0,
            100.0 * sizes[unit]["c"] / sizes[unit]["total"] if sizes[unit]["total"] else 100.0))
    c_bytes, total_bytes = byte_progress(functions)
    lines.append("| **TOTAL** | **%d** | **%d** | **%d** | **%d** | **%d** | **%.1f%%** | **%.2f%%** |" % (
        totals["c_decompiled_matched"], totals["asm_stub_matched"], totals["named"], totals["todo"],
        totals["total"], 100.0 * totals["c_decompiled_matched"] / totals["total"],
        100.0 * c_bytes / total_bytes if total_bytes else 0))
    lines += [
        "",
        "## Byte progress",
        "",
        "Function counts weigh every function equally, which flatters progress when",
        "the matched set is dominated by small wrappers. Bytes count real C only.",
        "",
        "| C matched bytes | Total code bytes | % |",
        "|---:|---:|---:|",
        "| **{:,}** | **{:,}** | **{:.2f}%** |".format(c_bytes, total_bytes, 100.0 * c_bytes / total_bytes),
    ]
    (ROOT / "PROGRESS.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print("PROGRESS.md -> C=%d/%d (%.1f%%), bytes=%s/%s (%.2f%%)" % (
        totals["c_decompiled_matched"], totals["total"],
        100.0 * totals["c_decompiled_matched"] / totals["total"],
        format(c_bytes, ","), format(total_bytes, ","), 100.0 * c_bytes / total_bytes))


if __name__ == "__main__":
    main()
