#define GetSeqArcSeqParam_0201ecbc NNS_SndArcGetSeqArcSeqCount
#define NNS_SndArcGetFileAddress_0201ee28 NNS_SndArcGetFileAddress
#define NNS_SndArcGetSeqArcInfo_0201ea64 NNS_SndArcGetSeqArcInfo
#define func_02021874 NNSi_SndSeqArcGetSeqCount
#include "src/arm9/library_nns_snd/GetSeqArcSeqParam_0201ecbc.c"
