#define NNS_SndPlayerCountPlayingSeqByPlayerNo_0201d6c0 NNS_SndPlayerCountPlayingSeqByPlayerNo
#define data_0205dcf8 sSndPlayers
#include "src/arm9/library_nns_snd/NNS_SndPlayerCountPlayingSeqByPlayerNo_0201d6c0.c"
