#define BankDisposeCallback_0201fa7c WaveArcDisposeCallback
#define SND_DestroyBank SND_DestroyWaveArc
#define SND_InvalidateBankData SND_InvalidateWaveData
#include "src/arm9/library_nns_snd/BankDisposeCallback_0201fa7c.c"
