#define AcquireRecordSlot_02051d3c AcquireRecordSlot
#define CountFlaggedCategorySelections_0206a45c CountFlaggedCategorySelections
#define IsCategoryEntryFlagSet_020699c8 IsCategoryEntryFlagSet
#define ReleaseRecordSlot_02051dfc ReleaseRecordSlot
#include "src/ov002/unclassified_helpers/CountFlaggedCategorySelections_0206a45c.c"
