#define FixedPointMultiply12 FX_Mul
#define InitInstanceFromTemplate_020bca70 InitInstanceFromTemplate
#define NNSi_FndAllocFromDefaultHeap_0202a178 NNSi_FndAllocFromDefaultHeap
#define func_01ff878c MIi_CpuCopyFast
#include "src/ov040/unclassified_helpers/InitInstanceFromTemplate_020bca70.c"
