#define InitPanelModel_020ccc44 InitPanelModel
#define func_0202ecf8 InitSharedRecordAndDispatch
#define selectJointAnimationBlend_0202f2cc selectJointAnimationBlend
#include "src/ov076/unclassified_helpers/InitPanelModel_020ccc44.c"
