#define SlotMenu_ClearSelectedSlot_020c88b4 SlotMenu_ClearSelectedSlot
#define SlotMenu_LockTouchUntilCommit_020c88dc SlotMenu_LockTouchUntilCommit
#define SlotMenu_ReloadSlot_020c6f60 SlotMenu_ReloadSlot
#define SlotMenu_UnequipSlotEntry_020c89e0 SlotMenu_UnequipSlotEntry
#include "src/ov076/unclassified_helpers/SlotMenu_ClearSelectedSlot_020c88b4.c"
