#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#define SlotMenu_ReleaseSprites_020c6c7c SlotMenu_ReleaseSprites
#include "src/ov076/unclassified_helpers/SlotMenu_ReleaseSprites_020c6c7c.c"
