#define SlotMenu_GetCursorMarkType_020c7208 SlotMenu_GetCursorMarkType
#define SlotMenu_IsSecondColumnMarked_020c51b0 SlotMenu_IsSecondColumnMarked
#include "src/ov076/unclassified_helpers/SlotMenu_IsSecondColumnMarked_020c51b0.c"
