#define ReleaseAndFreeResource_020a2abc ReleaseAndFreeResource
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#define func_0202a1c4 NNSi_FndFreeFromDefaultHeap
#include "src/ov020/unclassified_helpers/ReleaseAndFreeResource_020a2abc.c"
