#define CalcNsBtpAnimation_0201cc48 NNSi_G3dAnmCalcNsBtp
#define FindTexturePatternFrameEntry_0201ad5c NNSi_G3dGetTexPatAnmFV
#define GetTexturePatternPaletteName_0201ad34 NNSi_G3dGetTexPatAnmPlttNameByIdx
#define GetTexturePatternTextureName_0201ad0c NNSi_G3dGetTexPatAnmTexNameByIdx
#define SetPaletteAnimationResult_0201cbe4 SetPlttParamaters_
#define SetTextureAnimationResult_0201cb0c SetTexParamaters_
#include "src/arm9/library_nns_g3d/CalcNsBtpAnimation_0201cc48.c"
