#define ApplyAnimRootMotion_020cff8c ApplyAnimRootMotion
#define ComputeRootMotionDelta_020ce9d4 ComputeRootMotionDelta
#define GetLockTargetPosition_020cef64 GetLockTargetPosition
#define GetLongestTrackDuration_020aa524 GetLongestTrackDuration
#define VEC_Add_01ff9e0c VEC_Add
#define func_ov052_020cc2f0 ComputeApproachStep
#include "src/ov052/unclassified_helpers/ApplyAnimRootMotion_020cff8c.c"
