#define ExtendFieldAndNotifyCallback_020cb57c ExtendFieldAndNotifyCallback
#define ExtendIfGreater_020cc1ec ExtendIfGreater
#include "src/ov052/unclassified_helpers/ExtendFieldAndNotifyCallback_020cb57c.c"
