#define AnySubObjectFlagsActive_020cfb28 AnySubObjectFlagsActive
#define GetTransitionReaction_020ce01c GetTransitionReaction
#include "src/ov052/unclassified_helpers/GetTransitionReaction_020ce01c.c"
