#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#define ReleaseResourceSlotArray_020ca2e4 ReleaseResourceSlotArray
#include "src/ov052/unclassified_helpers/ReleaseResourceSlotArray_020ca2e4.c"
