#define ApplyModelSetAnimations_020a9c50 ApplyModelSetAnimations
#define ResetCueGroupBefore_020a8128 ResetCueGroupBefore
#define SetAnimationFrameAll_020cdfc0 SetAnimationFrameAll
#define TransitionState_020ac94c TransitionState
#include "src/ov052/unclassified_helpers/SetAnimationFrameAll_020cdfc0.c"
