#define ScrollDriftingElementsHorizontal_0206fff0 ScrollDriftingElementsHorizontal
#define ScrollDriftingElementsVertical_02070174 ScrollDriftingElementsVertical
#define UpdateDriftingElementsByMode_0206ffa0 UpdateDriftingElementsByMode
#include "src/ov015/ui/UpdateDriftingElementsByMode_0206ffa0.c"
