#define FindNearestReachableNode_020c8eac FindNearestReachableNode
#define JumpCursorToEntry_020cae58 JumpCursorToEntry
#define ShowEntryHeaderMessage_020cad14 ShowEntryHeaderMessage
#define ShowNextUnlockNotice_020cc9fc ShowNextUnlockNotice
#include "src/ov075/unclassified_helpers/JumpCursorToEntry_020cae58.c"
