#define FreeResourceBlocks_020bfa94 FreeResourceBlocks
#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#include "src/ov093/unclassified_helpers/FreeResourceBlocks_020bfa94.c"
