#define SetupMovieScreenHardware_020a831c SetupMovieScreenHardware
#define SetupSubScreenForMovie_020a7c58 SetupSubScreenForMovie
#define movie_video_hardware_setup_020a7b3c movie_video_hardware_setup
#include "src/ov022/video_playback/SetupMovieScreenHardware_020a831c.c"
