#define BuildActorStatusFlags_020ce5d4 BuildActorStatusFlags
#define FilterEnemyStatusFlags_020d6d44 FilterEnemyStatusFlags
#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#include "src/ov058/unclassified_helpers/FilterEnemyStatusFlags_020d6d44.c"
