#define RestoreEnemyHealthAndReset_020d6c0c RestoreEnemyHealthAndReset
#define SetClampedCursor_020a75d8 SetClampedCursor
#include "src/ov058/unclassified_helpers/RestoreEnemyHealthAndReset_020d6c0c.c"
