#define ComputeRootMotionDelta_020ce9d4 ComputeRootMotionDelta
#define SpawnEffectParticle_020af104 SpawnEffectParticle
#define SpawnUnitProjectile_020aea0c SpawnUnitProjectile
#define UpdateEffectOwnerMotion_020d3c00 UpdateEffectOwnerMotion
#include "src/ov055/object_factory/UpdateEffectOwnerMotion_020d3c00.c"
