#define FreeGraphicsResources_020bf3e0 FreeGraphicsResources
#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#include "src/ov091/panel_state/FreeGraphicsResources_020bf3e0.c"
