#define Gfx_Reset2DEngines ResetDisplayHardware
#define InitTitleDisplay_02063218 InitTitleDisplay
#define SetMasterBrightnessMain SetBrightnessAndSyncMain
#define SetMasterBrightnessSub SetSecondaryBrightness
#include "src/ov004/shared_engine/InitTitleDisplay_02063218.c"
