#define DestroyDisplayObject_020c37b4 DestroyDisplayObject
#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#include "src/ov041/animation/DestroyDisplayObject_020c37b4.c"
