#define ReleaseEmbeddedObject_020c277c ReleaseEmbeddedObject
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#include "src/ov041/unclassified_helpers/ReleaseEmbeddedObject_020c277c.c"
