#define SetFrameProcessingMode_02013bcc NNS_GfdInitFrmPlttVramManager
#define frame_callback_primary sDefaultAllocPlttVramFunc
#define frame_callback_secondary sDefaultFreePlttVramFunc
#define frame_processing_state sFrmPlttVramManager
#define func_02013c18 NNS_GfdAllocFrmPlttVram
#define func_02013d34 NNS_GfdFreeFrmPlttVram
#define func_02013d74 NNS_GfdResetFrmPlttVramState
#include "src/arm9/runtime_data_utilities/SetFrameProcessingMode_02013bcc.c"
