#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#define OnUnitHitEvent_020bcb30 OnUnitHitEvent
#define StartFreeModelSlot_020d7ebc StartFreeModelSlot
#include "src/ov030/shared_engine/OnUnitHitEvent_020bcb30.c"
