#define AdvanceModelSlotAnimations_020d7e74 AdvanceModelSlotAnimations
#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#define Handle_WritePayloadIfLive_0204db9c Handle_WritePayloadIfLive
#define RebindAnimTracks_020aef64 RebindAnimTracks_020aef84
#define RotateOffsetAroundY_020a9160 RotateOffsetAroundY
#define SpawnSoundSlot_0204da8c SpawnSoundSlot
#define SpawnTiltedProjectile_020bcb8c SpawnTiltedProjectile
#define StepEffectAnimation_020aebd4 StepEffectAnimation
#define StopSoundSeqHandle_0204dbe4 StopSoundSeqHandle
#define UpdateCarriedLauncher_020bc900 UpdateCarriedLauncher
#include "src/ov030/shared_engine/UpdateCarriedLauncher_020bc900.c"
