#define CARD_TryWaitRomAsync CARD_TryWaitBackupAsync
#define CARD_WaitRomAsync CARD_WaitBackupAsync
#define CardUnlockAfterKeyShare_020091b8 CARD_UnlockBackup
#include "src/arm9/library_nitro_card/CardUnlockAfterKeyShare_020091b8.c"
