#define LoadDefaultProjectionValues_0202a7b4 LoadDefaultProjectionValues
#define ResetCameraProjectionOverrides_020bb088 ResetCameraProjectionOverrides
#define g_screenState_020bb764 gContinueScreenContext
#include "src/ov037/unclassified_helpers/ResetCameraProjectionOverrides_020bb088.c"
