#define InitDriftParticleMotion_020afa40 InitDriftParticleMotion
#define StartCameraDriftFromParams_020c3b10 StartCameraDriftFromParams
#include "src/ov050/shared_engine/StartCameraDriftFromParams_020c3b10.c"
