#define AccumulateTextBoxScroll_020bdc04 AccumulateTextBoxScroll
#define ComputePageScrollOffset_020bdb98 ComputePageScrollOffset
#define MeasureScriptOperandText_020bdb5c MeasureScriptOperandText
#define MeasureScriptTextBox_020bdb20 MeasureScriptTextBox
#include "src/ov036/unclassified_helpers/AccumulateTextBoxScroll_020bdc04.c"
