#define ScriptVm_ReadTableOffsetPtr_020bdb00 ScriptVm_ReadTableOffsetPtr
#define ScriptVm_ResolveOperand_02025d08 ScriptVm_ResolveOperand
#include "src/ov036/shared_engine/ScriptVm_ReadTableOffsetPtr_020bdb00.c"
