#define ScriptCmd_WaitScreenLayerIdle_020be0ac ScriptCmd_WaitScreenLayerIdle
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#define func_ov036_020bd540 IsScreenLayerLoaded
#include "src/ov036/shared_engine/ScriptCmd_WaitScreenLayerIdle_020be0ac.c"
