#define ScriptCmd_SetCursorOverride_020be7d4 ScriptCmd_SetCursorOverride
#define ScriptVm_ReadOperandInt_02025de4 ScriptVm_ReadOperandInt
#define SetPanelCursorOverride_020bd9a4 SetPanelCursorOverride
#define func_0202b788 GetLanguageIndex
#include "src/ov036/shared_engine/ScriptCmd_SetCursorOverride_020be7d4.c"
