#define DestroyAllContainerElements_020b900c DestroyAllContainerElements
#define DestroyContainerElement_020b8fc0 DestroyContainerElement
#define NNS_FndGetNextListObject_02012a38 NNS_FndGetNextListObject
#include "src/ov027/resource_container/DestroyAllContainerElements_020b900c.c"
