#define DestroyObjectsAndRelease_020b8c58 DestroyObjectsAndRelease
#define Ov008_DestroyAllListObjects DestroyAllContainerElements
#include "src/ov027/shared_variants/DestroyObjectsAndRelease_020b8c58.c"
