#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseListElementBuffer_020b808c ReleaseListElementBuffer
#include "src/ov027/resource_container/ReleaseListElementBuffer_020b808c.c"
