#define FindPrevCharBoundary_0200b288 FSi_DecrementSjisPosition
#define FindPrevSeparator_0200b31c FSi_DecrementSjisPositionToSlash
#include "src/arm9/unclassified_helpers/FindPrevSeparator_0200b31c.c"
