#define AcquireRecordHandle_020adaf0 AcquireRecordHandle
#define AcquireSharedRecordState_020a9054 AcquireSharedRecordState
#define AppendIntrusiveListObject_020128d0 NNS_FndAppendListObject
#define FindListObjectByIdPrimary_020accbc FindListObjectByIdPrimary
#define NNSi_FndAllocFromDefaultHeap_0202a178 NNSi_FndAllocFromDefaultHeap
#include "src/ov021/object_state/AcquireRecordHandle_020adaf0.c"
