#define AdvanceObjHandleConfig_020aa2e8 AdvanceObjHandleConfig
#define BeginObjHandleCheck_020aa40c BeginObjHandleCheck
#define IsObjHandleRequirementMet_020aa4f0 IsObjHandleRequirementMet
#include "src/ov021/unclassified_helpers/AdvanceObjHandleConfig_020aa2e8.c"
