#define BuildNodeRecords_020ade6c BuildNodeRecords
#define NNSi_FndAllocFromDefaultHeap_0202a178 NNSi_FndAllocFromDefaultHeap
#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ParseNodeRecord_020aa720 ParseNodeRecord
#include "src/ov021/object_state/BuildNodeRecords_020ade6c.c"
