#define FindListObjectByIdPrimary_020accbc FindListObjectByIdPrimary
#define NNS_FndGetNextListObject_02012a38 NNS_FndGetNextListObject
#include "src/ov021/object_state/FindListObjectByIdPrimary_020accbc.c"
