#define FindListObjectByIdSecondary_020acce8 FindListObjectByIdSecondary
#define NNS_FndGetNextListObject_02012a38 NNS_FndGetNextListObject
#include "src/ov021/object_state/FindListObjectByIdSecondary_020acce8.c"
