#define AdvanceAnimationCounter_020ab468 AdvanceAnimationCounter
#define DispatchEntryKindHandlers_020aaea8 DispatchEntryKindHandlers
#define InitEntryPool_020aa9c4 InitEntryPool
#define NNSi_FndAllocFromDefaultHeap_0202a178 NNSi_FndAllocFromDefaultHeap
#define ProcessActiveEntries_020aaee0 ProcessActiveEntries
#define ReleaseEntryGroup_020aaf10 ReleaseEntryGroup
#define SpawnUnitFromDesc_020aad8c SpawnUnitFromDesc
#define UpdateEffectAnimationPhase_020ab564 UpdateEffectAnimationPhase
#define UpdateEffectMovePhase_020ab4ac UpdateEffectMovePhase
#define func_01ff89a8 MI_CpuCopy8
#include "src/ov021/object_state/InitEntryPool_020aa9c4.c"
