#define RebindModelAnimTracks_020ab2f0 RebindModelAnimTracks
#define RemoveAnimationFromRenderObject_02018850 NNS_G3dRenderObjRemoveAnmObj
#define selectJointAnimationBlend_0202f2cc selectJointAnimationBlend
#include "src/ov021/animation/RebindModelAnimTracks_020ab2f0.c"
