#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseCallbackOwnedBuffer_020aafac ReleaseCallbackOwnedBuffer
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#define ReleaseSceneObject_020ae6c8 ReleaseSceneObject
#define ReleaseSharedRecordState_020a9084 ReleaseSharedRecordState
#include "src/ov021/object_state/ReleaseSceneObject_020ae6c8.c"
