#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#define StopAndClearSoundEmitter_020a8e14 StopAndClearSoundEmitter
#define StopEntrySounds_020addcc StopEntrySounds
#include "src/ov021/shared_engine/StopEntrySounds_020addcc.c"
