#define NNSi_FndFreeFromDefaultHeap_0202a1c4 NNSi_FndFreeFromDefaultHeap
#define ReleaseResourceAndDetach_0202eee8 ReleaseResourceAndDetach
#define TeardownBigObj_020ac8cc TeardownBigObj
#include "src/ov021/unclassified_helpers/TeardownBigObj_020ac8cc.c"
