#define BeginObjHandleCheck_020aa40c BeginObjHandleCheck
#define IsObjHandleRequirementMet_020aa4f0 IsObjHandleRequirementMet
#define TriggerMatchingHandle_020aa39c TriggerMatchingHandle
#include "src/ov021/unclassified_helpers/TriggerMatchingHandle_020aa39c.c"
