#define AdvanceOwnerAnimation_020ab41c AdvanceOwnerAnimation
#define AdvancePulsingHitUnit_020d71f4 AdvancePulsingHitUnit
#define FindStrongestHit_020ab0c8 FindStrongestHit
#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#include "src/ov056/unclassified_helpers/AdvancePulsingHitUnit_020d71f4.c"
