#define AdvanceLinkedHitUnit_020d7c4c AdvanceLinkedHitUnit
#define AdvanceOwnerAnimation_020ab41c AdvanceOwnerAnimation
#define FindStrongestHit_020ab0c8 FindStrongestHit
#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#include "src/ov056/unclassified_helpers/AdvanceLinkedHitUnit_020d7c4c.c"
