#define ComputeAndApplyLevelScaledValue_020d4d5c ComputeAndApplyLevelScaledValue
#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#define NotifyOwnerThenApplyScaledValue_020d4dfc NotifyOwnerThenApplyScaledValue
#include "src/ov056/unclassified_helpers/NotifyOwnerThenApplyScaledValue_020d4dfc.c"
