#define FireAimedSlotProjectile_020d6900 FireAimedSlotProjectile
#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#define UpdateDelayedSlotProjectile_020d6a50 UpdateDelayedSlotProjectile
#define UpdateSceneGroupEntries_020aeb84 UpdateSceneGroupEntries
#include "src/ov056/unclassified_helpers/UpdateDelayedSlotProjectile_020d6a50.c"
