#define AwardPartyGaugePoints_0206ded8 AwardPartyGaugePoints
#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#define StepEffectAnimation_020aebd4 StepEffectAnimation
#define UpdateGaugeRewardEffect_020d4c80 UpdateGaugeRewardEffect
#include "src/ov056/unclassified_helpers/UpdateGaugeRewardEffect_020d4c80.c"
