#define AdvanceOwnerAnimation_020ab41c AdvanceOwnerAnimation
#define AdvanceToSecondPhase_020ab5f0 AdvanceToSecondPhase
#define FindStrongestHit_020ab0c8 FindStrongestHit
#define FixedPointMultiply12 FX_Mul
#define GetBoundedEntryField_0206db5c GetBoundedEntryField
#define ScaleVecFx32_01ffafb4 ScaleVecFx32
#define SteerTowardTarget_020ab1f0 SteerTowardTarget
#define UpdateHomingProjectile_020d2e60 UpdateHomingProjectile
#define VEC_Add_01ff9e0c VEC_Add
#define VEC_DotProduct_01ff9e6c VEC_DotProduct
#define VEC_MultAdd_01ffa09c VEC_MultAdd
#define VEC_Subtract_01ff9e3c VEC_Subtract
#define func_01ffa0f4 VEC_Distance
#include "src/ov056/shared_engine/UpdateHomingProjectile_020d2e60.c"
