#define GX_BeginLoadBGExtPltt_02007c50 GX_BeginLoadBGExtPltt
#define GX_DisableBankForBGExtPltt GX_ResetBankForBGExtPltt
#define data_02056f0c gGXExtPlttLoadState
#include "src/arm9/library_nitro_gx/func_02007c50.c"
