#define GX_ResetBankForBGExtPltt_02008e84 GX_DisableBankForBGExtPltt
#define data_02056f56 sGXBgExtPlttBank
#define resetBankForX_ disableBankForX_
#include "src/arm9/library_nitro_gx/GX_ResetBankForBGExtPltt_02008e84.c"
