#define GX_ResetBankForSubOBJExtPltt_02008f58 GX_DisableBankForSubOBJExtPltt
#define data_02056f60 sGXSubObjExtPlttBank
#define resetBankForX_ disableBankForX_
#include "src/arm9/library_nitro_gx/GX_ResetBankForSubOBJExtPltt_02008f58.c"
