#define GX_ResetBankForOBJExtPltt_02008ea8 GX_DisableBankForOBJExtPltt
#define data_02056f58 sGXObjExtPlttBank
#define resetBankForX_ disableBankForX_
#include "src/arm9/library_nitro_gx/GX_ResetBankForOBJExtPltt_02008ea8.c"
