#define GX_ResetBankForSubBGExtPltt_02008f30 GX_DisableBankForSubBGExtPltt
#define data_02056f5e sGXSubBgExtPlttBank
#define resetBankForX_ disableBankForX_
#include "src/arm9/library_nitro_gx/GX_ResetBankForSubBGExtPltt_02008f30.c"
