#define Camera_BuildSideView_020c2d8c Camera_BuildSideView
#define Camera_GetFocusPosition_020c1780 Camera_GetFocusPosition
#define Camera_GetPlayerBackDirection_020c2d5c Camera_GetPlayerBackDirection
#include "src/ov046/shared_engine/Camera_BuildSideView_020c2d8c.c"
